services:
  - type: web
    name: telegram-payment-bot
    env: python
    region: oregon  # or singapore, frankfurt, etc.
    plan: free
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        value: "7998689373:AAGUaTxrHzWabJvqZAUM2NjRQb1PHXpmGqA"
      - key: ADMIN_ID
        value: "7495749312"
      - key: DEPOSIT_REQUESTS_GROUP_ID
        value: "-1003687850459"
      - key: DEPOSIT_PENDING_GROUP_ID
        value: "-1003415130807"
      - key: DEPOSIT_COMPLETED_GROUP_ID
        value: "-1003513719508"
      - key: WITHDRAW_REQUESTS_GROUP_ID
        value: "-1003522192758"
      - key: WITHDRAW_COMPLETED_GROUP_ID
        value: "-1003637541728"
      - key: MONGO_URI
        value: "mongodb+srv://telegram-payment-bot:Jatin161@telegram-payment-bot.cabji2f.mongodb.net/?retryWrites=true&w=majority&serverSelectionTimeoutMS=10000&connectTimeoutMS=10000&socketTimeoutMS=10000"
